INSERT INTO USER11 (ID, NAME, AGE) VALUES (1, 'SATO TARO', 18);
INSERT INTO USER11 (ID, NAME, AGE) VALUES (2, 'TAKAHASHI JIRO', 20);
INSERT INTO USER11 (ID, NAME, AGE) VALUES (3, 'SUZUKI SABURO', 21);